// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoption.Api.Data;

#nullable disable

namespace PetAdoption.Api.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20240508073607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buddy is a loyal and friendly Golden Retriever. He enjoys playing fetch, going for long walks, and cuddling with his family.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Buddy",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = 1,
                            Breed = "Cat - Siamese",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Whiskers is a sleek and elegant Siamese cat. He enjoys lounging in sunny spots, chasing toys, and receiving affection from his human companions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Whiskers",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = 1,
                            Breed = "Dog - German Shepherd",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a brave and intelligent German Shepherd. He is highly trainable, loyal, and protective of his family. Rocky enjoys obedience training, playing games, and going on outdoor adventures.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Rocky",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = 1,
                            Breed = "Dog - Labrador Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Max is a friendly Labrador Retriever with a love for fetching. He enjoys spending time outdoors and playing with his favorite toys.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Max",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = 1,
                            Breed = "Dog - Beagle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daisy is a curious Beagle with a nose for adventure. She loves exploring new scents and going on long walks with her family.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Daisy",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = 1,
                            Breed = "Dog - Siberian Husky",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is an energetic Siberian Husky who thrives in cold climates. She enjoys running, hiking, and pulling sleds in the snow.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Luna",
                            Price = 500.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = 1,
                            Breed = "Dog - Poodle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Charlie is an elegant Poodle known for his intelligence and grace. He enjoys learning new tricks and showing off his skills.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Charlie",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = 1,
                            Breed = "Dog - Boxer",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bailey is a playful Boxer with a heart of gold. He loves romping around in the yard and chasing after balls with his boundless energy.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Bailey",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = 1,
                            Breed = "Dog - Shih Tzu",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bella is a charming Shih Tzu known for her affectionate nature. She enjoys cuddling on the couch and being pampered with grooming sessions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Bella",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = 1,
                            Breed = "Dog - Border Collie",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cooper is a friendly and intelligent Border Collie. He loves playing fetch and going for long walks.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Cooper",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = 1,
                            Breed = "Dog - Dachshund",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lucy is a playful Dachshund with a big heart. She enjoys cuddling on the couch and exploring new places.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Lucy",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = 1,
                            Breed = "Dog - Bulldog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toby is a loyal Bulldog who adores his family. He enjoys napping in the sun and chewing on his favorite toys.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Toby",
                            Price = 420.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = 1,
                            Breed = "Dog - Cocker Spaniel",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Molly is a gentle Cocker Spaniel who loves being pampered. She enjoys baths, brushing, and snuggling up with her humans.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Molly",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = 1,
                            Breed = "Dog - Rottweiler",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oscar is a strong and protective Rottweiler. He is great with kids and loves going on adventures in the great outdoors.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Oscar",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = 1,
                            Breed = "Dog - Shetland Sheepdog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zoe is a clever Shetland Sheepdog who excels in agility training. She is always up for a challenge and loves learning new tricks.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Zoe",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = 1,
                            Breed = "Dog - Australian Shepherd",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sam is an energetic Australian Shepherd who thrives on mental and physical stimulation. He enjoys herding and playing frisbee.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Sam",
                            Price = 500.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            AdoptionStatus = 1,
                            Breed = "Dog - Great Dane",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Riley is a majestic Great Dane with a gentle demeanor. Despite his size, he is a big softie who loves cuddling on the couch.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Riley",
                            Price = 600.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = 1,
                            Breed = "Dog - Pembroke Welsh Corgi",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lola is a charismatic Pembroke Welsh Corgi who charms everyone she meets. She enjoys herding and participating in dog sports.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Lola",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = 1,
                            Breed = "Dog - Bernese Mountain Dog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bentley is a friendly and affectionate Bernese Mountain Dog. He loves snowy days and pulling carts or sleds.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Bentley",
                            Price = 550.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = 1,
                            Breed = "Dog - Cavalier King Charles Spaniel",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sophie is a sweet and gentle Cavalier King Charles Spaniel. She adores cuddling and will follow her humans everywhere.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Sophie",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 21,
                            AdoptionStatus = 1,
                            Breed = "Dog - Doberman Pinscher",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zeus is a loyal and fearless Doberman Pinscher. He is highly trainable and excels in obedience and protection work.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Zeus",
                            Price = 480.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 22,
                            AdoptionStatus = 1,
                            Breed = "Dog - English Bulldog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sadie is a laid-back English Bulldog who loves lounging around the house. She has a playful side and enjoys short walks.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Sadie",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            AdoptionStatus = 1,
                            Breed = "Dog - Jack Russell Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jack is a spirited Jack Russell Terrier with endless energy. He loves chasing balls and exploring his surroundings.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Jack",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 24,
                            AdoptionStatus = 1,
                            Breed = "Dog - Pomeranian",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ruby is a fluffy and affectionate Pomeranian. She enjoys being the center of attention and will happily perform tricks for treats.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Ruby",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 25,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Doodle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teddy is a playful and outgoing Golden Doodle. He is great with kids and loves romping around in the backyard.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Teddy",
                            Price = 500.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 26,
                            AdoptionStatus = 1,
                            Breed = "Dog - Maltese",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maggie is a charming Maltese with a gentle disposition. She enjoys snuggling in blankets and going for leisurely walks.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Maggie",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 27,
                            AdoptionStatus = 1,
                            Breed = "Dog - Basset Hound",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jake is a laid-back Basset Hound with a nose for adventure. He loves following scents and lounging in sunny spots.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Jake",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 28,
                            AdoptionStatus = 1,
                            Breed = "Dog - Bull Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Roxy is a spunky Bull Terrier with a playful personality. She enjoys running around the yard and playing with toys.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Roxy",
                            Price = 420.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 29,
                            AdoptionStatus = 1,
                            Breed = "Dog - West Highland White Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gus is a spirited West Highland White Terrier known for his spunky attitude. He loves digging and exploring outdoors.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Gus",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 30,
                            AdoptionStatus = 1,
                            Breed = "Dog - Boxer",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bailey is a friendly and energetic Boxer. He enjoys playing fetch and going for runs with his human companions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Bailey",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 31,
                            AdoptionStatus = 1,
                            Breed = "Dog - Saint Bernard",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Holly is a gentle giant Saint Bernard known for her loving nature. She enjoys cuddling and being around people.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Holly",
                            Price = 600.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 32,
                            AdoptionStatus = 1,
                            Breed = "Dog - Labrador Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Max is a loyal and intelligent Labrador Retriever. He excels in obedience training and loves swimming and fetching.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Max",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 33,
                            AdoptionStatus = 1,
                            Breed = "Dog - French Bulldog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coco is an adorable French Bulldog with a big personality. She loves snuggling and entertaining her family with her antics.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Coco",
                            Price = 550.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 34,
                            AdoptionStatus = 1,
                            Breed = "Dog - Miniature Schnauzer",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is a playful Miniature Schnauzer with a mischievous streak. He enjoys learning new tricks and going for walks in the park.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Milo",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 35,
                            AdoptionStatus = 1,
                            Breed = "Dog - English Springer Spaniel",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lily is a loving and obedient English Springer Spaniel. She enjoys outdoor activities like hiking and playing fetch.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Lily",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 36,
                            AdoptionStatus = 1,
                            Breed = "Dog - Great Pyrenees",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apollo is a majestic Great Pyrenees known for his protective instincts. He loves snowy winters and patrolling his territory.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Apollo",
                            Price = 500.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 37,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buddy is a friendly and loyal Golden Retriever. He enjoys swimming, fetching, and spending time with his family.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Buddy",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 38,
                            AdoptionStatus = 1,
                            Breed = "Dog - Poodle",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Charlie is a smart and elegant Poodle with a playful spirit. He enjoys learning new tricks and going for walks in the park.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Charlie",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 39,
                            AdoptionStatus = 1,
                            Breed = "Dog - Australian Cattle Dog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bailey is an intelligent and energetic Australian Cattle Dog. She enjoys agility training and hiking adventures.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Bailey",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 40,
                            AdoptionStatus = 1,
                            Breed = "Dog - Weimaraner",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Duke is a noble Weimaraner known for his grace and athleticism. He enjoys outdoor activities and bonding with his family.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Duke",
                            Price = 480.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 41,
                            AdoptionStatus = 1,
                            Breed = "Dog - Bichon Frise",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mia is a cheerful Bichon Frise with a love for life. She enjoys playing games and spending time with her human companions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Mia",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 42,
                            AdoptionStatus = 1,
                            Breed = "Dog - German Shepherd",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a courageous and loyal German Shepherd. He excels in obedience training and enjoys being challenged mentally and physically.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Rocky",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 43,
                            AdoptionStatus = 1,
                            Breed = "Dog - American Eskimo Dog",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Princess is a playful American Eskimo Dog with a fluffy white coat. She enjoys learning tricks and going for walks in the snow.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Princess",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 44,
                            AdoptionStatus = 1,
                            Breed = "Dog - Alaskan Malamute",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sasha is a strong and independent Alaskan Malamute. She loves cold weather and enjoys pulling sleds and carts.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Sasha",
                            Price = 550.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 45,
                            AdoptionStatus = 1,
                            Breed = "Dog - Border Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Shadow is a brave and adventurous Border Terrier. He enjoys exploring the great outdoors and chasing small animals.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Shadow",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 46,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is a lovable Golden Retriever with a heart of gold. He enjoys playing fetch and swimming in the lake.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Milo",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 47,
                            AdoptionStatus = 1,
                            Breed = "Dog - Siberian Husky",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is an energetic Siberian Husky with striking blue eyes. She loves running and playing in the snow.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Luna",
                            Price = 500.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 48,
                            AdoptionStatus = 1,
                            Breed = "Dog - Staffordshire Bull Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dexter is a strong and determined Staffordshire Bull Terrier. He enjoys training sessions and playing with his favorite toys.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Dexter",
                            Price = 420.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 49,
                            AdoptionStatus = 1,
                            Breed = "Dog - Yorkshire Terrier",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ruby is a sassy Yorkshire Terrier with a big personality. She loves being the center of attention and going for walks.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Ruby",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 50,
                            AdoptionStatus = 1,
                            Breed = "Dog - Shih Tzu",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teddy is a fluffy Shih Tzu with a sweet disposition. He enjoys cuddling on the couch and getting pampered with grooming sessions.",
                            Gender = 0,
                            IsActive = true,
                            Name = "Teddy",
                            Price = 300.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoption");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserAdoption", b =>
                {
                    b.HasOne("PetAdoption.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetAdoption.Api.Data.Entities.UserFavorites", b =>
                {
                    b.HasOne("PetAdoption.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoption.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
